#!/usr/bin/env bash
#
# Build the .deb by assembling the tree and calling dpkg-deb.
#
# Deliberately not debhelper. The package is architecture-independent pure
# Python with a handful of data files, so the whole payload fits in this script,
# where it can be read and verified. dh-python would add build dependencies and
# a layer of generated behaviour for no benefit at this size, and this package
# is distributed from GitHub Releases rather than through the Debian archive.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-$ROOT/dist}"

PACKAGE="translate-linux"
APP_ID="io.github.reginaldomorais.TranslateLinux"

VERSION="$(sed -n 's/^__version__ = "\(.*\)"$/\1/p' "$ROOT/src/translate_linux/__init__.py")"
if [[ -z "$VERSION" ]]; then
    echo "could not read __version__" >&2
    exit 1
fi

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

SITE="$STAGE/usr/lib/python3/dist-packages"
mkdir -p "$SITE" \
         "$STAGE/DEBIAN" \
         "$STAGE/usr/bin" \
         "$STAGE/usr/share/applications" \
         "$STAGE/usr/share/glib-2.0/schemas" \
         "$STAGE/usr/share/icons/hicolor/scalable/apps" \
         "$STAGE/usr/share/doc/$PACKAGE"

# --- python package -------------------------------------------------------
cp -r "$ROOT/src/translate_linux" "$SITE/"
find "$SITE" -name '__pycache__' -type d -prune -exec rm -rf {} +

# --- entry point ----------------------------------------------------------
cat > "$STAGE/usr/bin/$PACKAGE" <<'LAUNCHER'
#!/usr/bin/python3
import sys

from translate_linux.cli import main

sys.exit(main())
LAUNCHER
chmod 0755 "$STAGE/usr/bin/$PACKAGE"

# --- data -----------------------------------------------------------------
install -m 0644 "$ROOT/data/$PACKAGE.desktop" "$STAGE/usr/share/applications/"
install -m 0644 "$ROOT/data/$APP_ID.gschema.xml" "$STAGE/usr/share/glib-2.0/schemas/"
install -m 0644 "$ROOT/data/icons/hicolor/scalable/apps/$PACKAGE.svg" \
        "$STAGE/usr/share/icons/hicolor/scalable/apps/"
install -m 0644 "$ROOT/README.md" "$STAGE/usr/share/doc/$PACKAGE/"
install -m 0644 "$ROOT/LICENSE" "$STAGE/usr/share/doc/$PACKAGE/copyright"
gzip -9n -c "$ROOT/CHANGELOG.md" > "$STAGE/usr/share/doc/$PACKAGE/changelog.gz"

# --- control --------------------------------------------------------------
sed "s/@VERSION@/$VERSION/" "$ROOT/packaging/control.in" > "$STAGE/DEBIAN/control"
{
    echo "Installed-Size: $(du -ks "$STAGE" | cut -f1)"
} >> "$STAGE/DEBIAN/control"

install -m 0755 "$ROOT/packaging/postinst" "$STAGE/DEBIAN/postinst"
install -m 0755 "$ROOT/packaging/postrm" "$STAGE/DEBIAN/postrm"

# The schema is regenerated by postinst, so shipping a compiled one would go
# stale the moment another package touches the directory.
find "$STAGE" -name 'gschemas.compiled' -delete

# --- build ----------------------------------------------------------------
mkdir -p "$OUT_DIR"
ARTEFACT="$OUT_DIR/${PACKAGE}_${VERSION}_all.deb"
dpkg-deb --root-owner-group --build "$STAGE" "$ARTEFACT" >/dev/null

echo "$ARTEFACT"
